<a href="https://colab.research.google.com/github/kilaparthisatyasree-cyber/-y--s.Python/blob/main/unit3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Create a 2D array
arr = np.array([[10, 25, 30],
                [45, 50, 60],
                [5, 75, 20]])

print("Array:\n", arr)

# Find maximum and minimum values
max_value = np.max(arr)
min_value = np.min(arr)

# Find indices of maximum and minimum values (flattened array)
max_index = np.argmax(arr)
min_index = np.argmin(arr)

print("\nMaximum value:", max_value)
print("Index of maximum value:", max_index)

print("\nMinimum value:", min_value)
print("Index of minimum value:", min_index)

# Indices along axis (row-wise and column-wise)
print("\nIndex of maximum values along axis=0 (columns):", np.argmax(arr, axis=0))
print("Index of maximum values along axis=1 (rows):", np.argmax(arr, axis=1))


Array:
 [[10 25 30]
 [45 50 60]
 [ 5 75 20]]

Maximum value: 75
Index of maximum value: 7

Minimum value: 5
Index of minimum value: 6

Index of maximum values along axis=0 (columns): [1 2 1]
Index of maximum values along axis=1 (rows): [2 2 1]


In [3]:
# Program (b): To test whether none of the elements of a given array is zero
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Check if none of the elements are zero using np.all()
result = np.all(arr)

# Display the result
print("Array:", arr)
print("None of the elements are zero:", result)


Array: [1 2 3 4 5]
None of the elements are zero: True


In [2]:
# Program (c): To perform element-wise comparison of two arrays
import numpy as np

# Create two arrays
x = np.array([2, 5, 8, 10])
y = np.array([3, 5, 7, 10])

print("Array x:", x)
print("Array y:", y)

# Element-wise comparisons
print("\nGreater (x > y):")
print(np.greater(x, y))

print("\nGreater Equal (x >= y):")
print(np.greater_equal(x, y))

print("\nLess (x < y):")
print(np.less(x, y))

print("\nLess Equal (x <= y):")
print(np.less_equal(x, y))

print("\nEqual (x == y):")
print(np.equal(x, y))

print("\nEqual within tolerance (np.allclose):")
print(np.allclose(x, y, atol=1))


Array x: [ 2  5  8 10]
Array y: [ 3  5  7 10]

Greater (x > y):
[False False  True False]

Greater Equal (x >= y):
[False  True  True  True]

Less (x < y):
[ True False False False]

Less Equal (x <= y):
[ True  True False  True]

Equal (x == y):
[False  True False  True]

Equal within tolerance (np.allclose):
True


In [1]:
import numpy as np

# Scalar addition
np.add(1.0, 4.0)
# Output: 5.0

# Array addition
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.add(x1, x2)
# Output:
# array([[ 0.,  2.,  4.],
#        [ 3.,  5.,  7.],
#        [ 6.,  8., 10.]])

# Using '+' operator (shorthand for np.add)
x1 + x2
# Output same as np.add

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])